version: "3"
services:
    test-bizcuit_web_dev:
        container_name: test-bizcuit_web_dev
        build: 
            context: .
            dockerfile: Dockerfile.dev
        ports:
            - "3000:3000"
        volumes:
            - .:/app
            - /app/node_modules
        networks:
            - core-network
networks:
    core-network:
        driver: bridge

            
